### ISSUE TITLE
这个是不是还得继承 JobConsumer  来消费消息

### ISSUE THREAD

**Issue by anhao** [friendsofhyperf/amqp-job#3]
我这边测试继承 Job 投递消息后并没有消费消息,只是把消息投递了

**Comment by huangdijia** [comment]
是的，已经更新 readme

**Comment by anhao** [comment]
如果能实现自动将消费者注册的话就简单多了 ，就不用重复创建 Consumer ，直接创建 job，和Laravel一样

https://github.com/hyperf/hyperf/blob/master/src/amqp/src/ConsumerManager.php#L30

**Comment by huangdijia** [comment]
本身也是基于 hyperf 的，受限于 amqp 本身的复杂配置（交换机、路由、队列、进程数等等），自定义配置会灵活些。

或者看你有没有什么想法，欢迎 PR

**Comment by anhao** [comment]
就是这种 https://github.com/anhao/components/tree/3.x/src/amqp-job

不过遇到一个问题，消费完消息后，相关的队列Process会自动重启

**Comment by anhao** [comment]
提交了一个PR , https://github.com/friendsofhyperf/components/pull/720

**Comment by huangdijia** [comment]
> 提交了一个PR , https://github.com/friendsofhyperf/components/pull/720

我也刚提交了一个

**Comment by huangdijia** [comment]
> 就是这种 https://github.com/anhao/components/tree/3.x/src/amqp-job
> 
> 不过遇到一个问题，消费完消息后，相关的队列Process会自动重启

https://github.com/friendsofhyperf/amqp-job/releases/tag/v3.1.45

可以试试还有没有重启的问题

**Comment by anhao** [comment]
> > 就是这种 https://github.com/anhao/components/tree/3.x/src/amqp-job
> > 不过遇到一个问题，消费完消息后，相关的队列Process会自动重启
> 
> https://github.com/friendsofhyperf/amqp-job/releases/tag/v3.1.45
> 
> 可以试试还有没有重启的问题

这个版本是正常的，不会重启

**Comment by huangdijia** [comment]
好的

**Comment by anhao** [comment]
之前应该是因为 maxConsumption 默认设置的1导致的吧

**Comment by huangdijia** [comment]
> 之前应该是因为 maxConsumption 默认设置的1导致的吧

是的
