### ISSUE TITLE
请问如何使用延时任务

### ISSUE THREAD

**Issue by ywpusevpn** [friendsofhyperf/amqp-job#4]
麻烦大佬给一个延时任务的demo

**Comment by huangdijia** [comment]
amqp 要实现延迟比较复杂，建议用 [hyperf/async-queue](/hyperf/async-queue) 实现，实在需要，请参考 https://hyperf.wiki/3.1/#/zh-cn/amqp?id=%e5%bb%b6%e6%97%b6%e9%98%9f%e5%88%97
